"""create_initial_schema

Revision ID: 960fe962a5ac
Revises: 
Create Date: 2026-09-23 17:31:58.606633
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960fe962a5ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_table('major_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_centers_name'), 'major_centers', ['name'], unique=False)
    op.create_index(op.f('ix_major_centers_status'), 'major_centers', ['status'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_index(op.f('ix_persons_status'), 'persons', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_name'), 'reports', ['name'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_reporting_period_end'), 'reports', ['reporting_period_end'], unique=False)
    op.create_index(op.f('ix_reports_reporting_period_start'), 'reports', ['reporting_period_start'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('satsang_ghars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satsang_ghars_name'), 'satsang_ghars', ['name'], unique=False)
    op.create_index(op.f('ix_satsang_ghars_status'), 'satsang_ghars', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_data_source_id'), 'documents', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_original_filename'), 'documents', ['original_filename'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_content_hash'), 'document_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_status'), 'document_versions', ['status'], unique=False)
    op.create_table('source_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('cell_or_range', sa.String(length=100), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_references_document_id'), 'source_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_source_references_document_version_id'), 'source_references', ['document_version_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('satsang_ghar_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_reference_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['satsang_ghar_id'], ['satsang_ghars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_date'), 'assignments', ['date'], unique=False)
    op.create_index(op.f('ix_assignments_person_id'), 'assignments', ['person_id'], unique=False)
    op.create_index(op.f('ix_assignments_role_id'), 'assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_assignments_satsang_ghar_id'), 'assignments', ['satsang_ghar_id'], unique=False)
    op.create_index(op.f('ix_assignments_source_reference_id'), 'assignments', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('satsang_ghar_id', sa.UUID(), nullable=True),
    sa.Column('count_value', sa.Integer(), nullable=True),
    sa.Column('raw_value', sa.String(length=255), nullable=True),
    sa.Column('source_reference_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['satsang_ghar_id'], ['satsang_ghars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_satsang_ghar_id'), 'attendances', ['satsang_ghar_id'], unique=False)
    op.create_index(op.f('ix_attendances_source_reference_id'), 'attendances', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_table('vehicle_wheel_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('satsang_ghar_id', sa.UUID(), nullable=True),
    sa.Column('count_value', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('raw_value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_reference_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['satsang_ghar_id'], ['satsang_ghars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_wheel_data_date'), 'vehicle_wheel_data', ['date'], unique=False)
    op.create_index(op.f('ix_vehicle_wheel_data_satsang_ghar_id'), 'vehicle_wheel_data', ['satsang_ghar_id'], unique=False)
    op.create_index(op.f('ix_vehicle_wheel_data_source_reference_id'), 'vehicle_wheel_data', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_vehicle_wheel_data_status'), 'vehicle_wheel_data', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_wheel_data_vehicle_type'), 'vehicle_wheel_data', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_wheel_data_vehicle_type'), table_name='vehicle_wheel_data')
    op.drop_index(op.f('ix_vehicle_wheel_data_status'), table_name='vehicle_wheel_data')
    op.drop_index(op.f('ix_vehicle_wheel_data_source_reference_id'), table_name='vehicle_wheel_data')
    op.drop_index(op.f('ix_vehicle_wheel_data_satsang_ghar_id'), table_name='vehicle_wheel_data')
    op.drop_index(op.f('ix_vehicle_wheel_data_date'), table_name='vehicle_wheel_data')
    op.drop_table('vehicle_wheel_data')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_source_reference_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_satsang_ghar_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_source_reference_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_satsang_ghar_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_role_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_person_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_date'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_source_references_document_version_id'), table_name='source_references')
    op.drop_index(op.f('ix_source_references_document_id'), table_name='source_references')
    op.drop_table('source_references')
    op.drop_index(op.f('ix_document_versions_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_content_hash'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_original_filename'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_data_source_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_satsang_ghars_status'), table_name='satsang_ghars')
    op.drop_index(op.f('ix_satsang_ghars_name'), table_name='satsang_ghars')
    op.drop_table('satsang_ghars')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporting_period_start'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporting_period_end'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_name'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_persons_status'), table_name='persons')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_major_centers_status'), table_name='major_centers')
    op.drop_index(op.f('ix_major_centers_name'), table_name='major_centers')
    op.drop_table('major_centers')
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
